// AUTO-GENERATED by scripts/gen-images.mjs
export const images = {
  "/Projects/laser-cutting/laser-cutting-1.webp": {
    "default": "/Projects/laser-cutting/laser-cutting-1.webp"
  },
  "/Projects/laser-cutting/laser-cutting-2.webp": {
    "default": "/Projects/laser-cutting/laser-cutting-2.webp"
  },
  "/Projects/laser-cutting/laser-cutting-3.webp": {
    "default": "/Projects/laser-cutting/laser-cutting-3.webp"
  },
  "/Projects/lory-lct/lory-lct-1.webp": {
    "default": "/Projects/lory-lct/lory-lct-1.webp"
  },
  "/Projects/lory-lct/lory-lct-2.webp": {
    "default": "/Projects/lory-lct/lory-lct-2.webp"
  },
  "/Projects/lory-lct/lory-lct-3.webp": {
    "default": "/Projects/lory-lct/lory-lct-3.webp"
  },
  "/Projects/lory.lab/lory-lab-1.webp": {
    "default": "/Projects/lory.lab/lory-lab-1.webp"
  },
  "/Projects/lory.lab/lory-lab-10.webp": {
    "default": "/Projects/lory.lab/lory-lab-10.webp"
  },
  "/Projects/lory.lab/lory-lab-11.webp": {
    "default": "/Projects/lory.lab/lory-lab-11.webp"
  },
  "/Projects/lory.lab/lory-lab-12.webp": {
    "default": "/Projects/lory.lab/lory-lab-12.webp"
  },
  "/Projects/lory.lab/lory-lab-13.webp": {
    "default": "/Projects/lory.lab/lory-lab-13.webp"
  },
  "/Projects/lory.lab/lory-lab-2.webp": {
    "default": "/Projects/lory.lab/lory-lab-2.webp"
  },
  "/Projects/lory.lab/lory-lab-3.webp": {
    "default": "/Projects/lory.lab/lory-lab-3.webp"
  },
  "/Projects/lory.lab/lory-lab-4.webp": {
    "default": "/Projects/lory.lab/lory-lab-4.webp"
  },
  "/Projects/lory.lab/lory-lab-5.webp": {
    "default": "/Projects/lory.lab/lory-lab-5.webp"
  },
  "/Projects/lory.lab/lory-lab-6.webp": {
    "default": "/Projects/lory.lab/lory-lab-6.webp"
  },
  "/Projects/lory.lab/lory-lab-7.webp": {
    "default": "/Projects/lory.lab/lory-lab-7.webp"
  },
  "/Projects/lory.lab/lory-lab-8.webp": {
    "default": "/Projects/lory.lab/lory-lab-8.webp"
  },
  "/Projects/lory.lab/lory-lab-9.webp": {
    "default": "/Projects/lory.lab/lory-lab-9.webp"
  },
  "/Projects/tours-of-yakutia/tours-of-yakutia-1.webp": {
    "default": "/Projects/tours-of-yakutia/tours-of-yakutia-1.webp"
  },
  "/Projects/tours-of-yakutia/tours-of-yakutia-2.webp": {
    "default": "/Projects/tours-of-yakutia/tours-of-yakutia-2.webp"
  },
  "/Projects/tours-of-yakutia/tours-of-yakutia-3.webp": {
    "default": "/Projects/tours-of-yakutia/tours-of-yakutia-3.webp"
  },
  "/Projects/tours-of-yakutia/tours-of-yakutia-4.webp": {
    "default": "/Projects/tours-of-yakutia/tours-of-yakutia-4.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-1.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-1.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-2.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-2.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-3.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-3.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-4.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-4.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-5.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-5.webp"
  },
  "/Projects/ykt-sokol/ykt-sokol-6.webp": {
    "default": "/Projects/ykt-sokol/ykt-sokol-6.webp"
  }
} as Record<string, { default: string }>;
