import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
// ВАЖНО: Projects с большой буквы, как в репо
const dir = path.join(root, "public", "Projects");

function walk(d) {
  const out = [];
  for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (/\.(png|jpg|jpeg|webp|avif)$/i.test(entry.name)) out.push(p);
  }
  return out;
}

const files = fs.existsSync(dir) ? walk(dir) : [];

// Сделаем "vite-подобный" eager glob результат:
// { "/Projects/x.webp": { default: "/Projects/x.webp" }, ... }
const obj = {};
for (const abs of files) {
  const webPath =
    "/" + path.relative(path.join(root, "public"), abs).split(path.sep).join("/");
  obj[webPath] = { default: webPath };
}

const outFile = path.join(root, "src", "shared", "images.generated.ts");
fs.mkdirSync(path.dirname(outFile), { recursive: true });

const content = `// AUTO-GENERATED by scripts/gen-images.mjs
export const images = ${JSON.stringify(obj, null, 2)} as Record<string, { default: string }>;
`;

fs.writeFileSync(outFile, content);
console.log(`Generated ${Object.keys(obj).length} images -> ${outFile}`);